AlgoBooster/AlgoBooster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('ab_ui.urls', namespace='ab_ui')),
	#path('admin/', admin.site.urls),
]

AlgoBooster/ab_ui/urls.py
from django.urls import path
from . import views

app_name = 'ab_ui'
urlpatterns = [
	path('', views.index, name='index'),
	path('algobooster/', views.algobooster, name='algobooster'),
	path('algobooster/submit/', views.submit, name='submit'),
	path('training/', views.training, name='training'),
	path('training/submit/', views.train, name='train'),
	path('about', views.about, name='about'),
	path('imprint', views.imprint, name='imprint'),
	path('disclaimer', views.disclaimer, name='disclaimer'),
]

AlgoBooster/ab_ui/models.py
from django.db import models

class AlgorithmData(models.Model):
    """ General class for algorithm attributes (prediction case). """

    rec_count = models.IntegerField()
    loop_n_depend = models.IntegerField()
    loop_nested = models.IntegerField()
    loop_type = models.IntegerField()
    prog_terminate = models.IntegerField()
    using_non_scalar = models.IntegerField()
    repeat_values = models.IntegerField()
    reuse_values = models.IntegerField()
    complexity = models.IntegerField()
        
    def initAttr(self, attr_list):
        """ Initializes the algorithm attributes.

        Keyword arguments:
        self -- the AlgorithmData instance
        attr_list -- dictionary containing the names and values of the attributes for this instance
        """
        self.rec_count = attr_list.get('RecCount')
        self.loop_n_depend = attr_list.get('LoopNDepend')
        self.loop_nested = attr_list.get('LoopNested')
        self.loop_type = attr_list.get('LoopType')
        self.prog_terminate = attr_list.get('ProgTerminate')
        self.using_non_scalar = attr_list.get('UsingNonScalar')
        self.repeat_values = attr_list.get('RepeatValues')
        self.reuse_values = attr_list.get('ReuseValues')
        self.complexity = attr_list.get('Complexity')

    def getValues(self):
        """ Returns the attributes of the instance as dictionary.

        Keyword arguments:
        self -- the AlgorithmData instance
        """
        attr_list = {}
        attr_list['RecCount'] = self.rec_count
        attr_list['LoopNDepend'] = self.loop_n_depend
        attr_list['LoopNested'] = self.loop_nested
        attr_list['LoopType'] = self.loop_type
        attr_list['ProgTerminate'] = self.prog_terminate
        attr_list['UsingNonScalar'] = self.using_non_scalar
        attr_list['RepeatValues'] = self.repeat_values
        attr_list['ReuseValues'] = self.reuse_values
        attr_list['Complexity'] = self.complexity
        return attr_list


    def __str__(self):
        """ Returns a string representing the instance.

        Keyword arguments:
        self -- the AlgorithmData instance
        """
        return 'RecCount:' + str(self.rec_count) + ', ' + \
             'LoopNDepend:' + str(self.loop_n_depend) + ", " + \
             'LoopNested:' + str(self.loop_nested) + ", " + \
             'LoopType:' + str(self.loop_type) + ", " + \
             'ProgTerminate:' + str(self.prog_terminate) + ", " + \
             'UsingNonScalar:' + str(self.using_non_scalar) + ", " + \
             'RepeatValues:' + str(self.repeat_values) + ", " + \
             'ReuseValues:' + str(self.reuse_values) + ", " + \
             'Complexity:' + str(self.complexity)
                 

class TrainData(AlgorithmData):
    """ Extended class for algorithm attributes, also containing the classification (training case). """

    classification = models.IntegerField(default=0)

    def initAttr(self, attr_list, classification):
        """ Initializes the algorithm attributes.

        Keyword arguments:
        self -- the AlgorithmData instance
        attr_list -- dictionary containing the names and values of the attributes for this instance
        """

        super().initAttr(attr_list)
        self.classification = classification

    def getValues(self):
        """ Returns the attributes of the instance as dictionary.

        Keyword arguments:
        self -- the AlgorithmData instance
        """

        attr_list = super().getValues()
        attr_list['Classification'] = self.classification
        return attr_list

    def __str__(self):
        """ Returns a string representing the instance.

        Keyword arguments:
        self -- the AlgorithmData instance
        """

        return super().__str__() + ', Classification:' + str(self.classification)

AlgoBooster/ab_ui/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader, RequestContext
from django import forms
from ab_ui.ab_main import ab_controller as main

def index(request):
	""" View function for the index page. """
	return render(request, 'ab_ui/index.html')

def about(request):
	""" View function for the about page. """
	return render(request, 'ab_ui/about.html')

def imprint(request):
	""" View function for the imprint page. """
	return render(request, 'ab_ui/imprint.html')

def disclaimer(request):
	""" View function for the disclaimer page. """
	return render(request, 'ab_ui/disclaimer.html')

def algobooster(request):
	""" View function for the 'Use Algobooster' page. (GET) """
	return render(request, 'ab_ui/algobooster.html')

def training(request):
	""" View function for the 'Train Algobooster' page. (GET) """
	return render(request, "ab_ui/training.html")
 
def train(request):
	""" View function for submitting code and classification to the 'Train Algobooster' page. (POST) """
	# Read the input pseudocode
	code = request.POST.get('code')

	# Read the classification
	try:
		classification = str(request.POST.get("classification"))
	except TypeError:
		context = {
			'result': "Error while reading classification."
		}
		return render(request, "ab_ui/training.html", context)
		

	# Train machine learning system with the code and classification
	result = main.trainAB(code, classification)

	context = {
		'result': result,
		'input': code,
		'classification': classification
	}
	return render(request, "ab_ui/training.html", context)

def submit(request):
	""" View function for submitting code to the 'Use Algobooster' page. (POST) """
	# Read the input pseudocode
	code = request.POST.get('code')


	# Method to prepare Python for html
	def prepare_html(pre_string):
		pre_string = pre_string.replace('\n', "<br />")
		pre_string = pre_string.replace('\t', "&nbsp;&nbsp;&nbsp;&nbsp;")
		return pre_string

	# Check submit type
	subType = request.POST.get('submitType')

	# forward the code to Algobooster
	if subType == "parse_and_class":
		ab_result = main.startAB(code) 
	else:
		ab_result = main.startAB(code, True)

	context = {
		'code': prepare_html(ab_result.get('code')),
		'complexity': prepare_html(ab_result.get('complexity')),
		'classification': prepare_html(ab_result.get('classification')),
		'probability': prepare_html(ab_result.get('probability')),
		'tips': prepare_html(ab_result.get('tips')),
		'input': code
	}
	
	return render(request, 'ab_ui/algobooster.html', context)

AlgoBooster/ab_ui/templates/ab_ui/about.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
		<div class="col">
			<br /><br />
			<h3>About Algobooster</h3>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<br /><br />

                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
		</div>
	</div>
	<div class="row">
			<div class="col">
				<br /><br />
				<h5>Get to the Application <a href="">right away</a>
					and test your very own algorithm.</h5>
				<br /><br />
			</div>
		</div>


{% endblock %}

AlgoBooster/ab_ui/templates/ab_ui/algobooster.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
	<div class="col">
		<br />
		<h3>Use AlgoBooster</h3>
		<br />
	</div>
</div>

<div class="row">
	<div class="col">
		<!-- choose tip category -->
		<b>Tools</b><br />
		<div class="tools btn-group" role="group">
			<button type="button" class="btn" id="var">Variables</button>
			<button type="button" class="btn" id="cond">Conditions</button>
			<button type="button" class="btn" id="loop">Loops</button>
			<button type="button" class="btn" id="func">Functions</button>	
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-3 col-12">
		<!-- Tips for using the pseudo code language -->
		<div class="components box">
			<div id="comp-content">
				<div id="var-content">
					<b>Variables</b><br />

					You can do assignments like the following: <br />
					<code>
						a <- 3<br />
						b <- {1, 2, 3}<br />
						c <- [1, 2, 3]<br />
						d <- a<br />
						e <- b[1]<br />
						c[0] <- d<br />
					</code>
					<br />

					Additionally, you can do basic calculations: <br />
					<code>
						a <- 3 + 2<br />
						b <- 2 % 3<br />
						c <- 2 / 3<br />
						d <- 2 // 3<br />
						e <- 2 * 3<br />
						f <- 2^3<br />
					</code><br />
					
					Of course, you can also use variable names or lists / sets
					with indices instead of numbers in the calculations.
				</div>
				<div id="cond-content">
					<b>Conditions</b><br />
					You can either use:<br />
					<code>
						if <i>cond</i> then <i>code</i> endif
					</code>
					<br />
					or: 
					<br />
					<code>
						if <i>cond</i> then <i>code</i> else <i>code</i> endif
					</code>
					<br />
					with a condition like
					<br />
					<code>
						not(<i>term</i>)<br />
						<i>term</i><br />
						<i>term</i> == <i>term</i><br />
						<i>term</i> != <i>term</i><br />
						<i>term</i> > <i>term</i><br />
						<i>term</i> >= <i>term</i><br />
						<i>term</i> < <i>term</i><br />
						<i>term</i> <= <i>term</i><br />
						<i>term</i> in <i>term</i><br />
						<i>term</i> not in <i>term</i><br />
					</code>

					where <code><i>term</i></code> can be a variable, set, sequence, element
					of a set or sequence, number or function call.<br /><br />

					Additionally, you can logically link two or more conditions 
					like the following: 
					<br />
					<code>
						<i>cond</i> and <i>cond</i><br />
						<i>cond</i> or <i>cond</i><br />
					</code>

				</div>
				<div id="loop-content">
					<b>Loops</b><br />

					Currently, there are two possible loops.<br /><br />

					The first one is a <code>repeat-until</code> loop:<br />
					<code>
						repeat <i>code</i> until <i>condition</i>
					</code>
					<br />

					where <code><i>condition</i></code> is built as shown in the 
					section "Conditions".<br /><br />

					The second one is a <code>for</code> loop: <br />
					<code>
						for <i>for-condition</i> do <i>code</i> endfor
					</code>
					<br />

					where <code><i>for-condition</i></code> can look like the following:<br />
					<code>
						<i>name</i> in <i>value</i> to <i>value</i> by <i>value</i><br />
						<i>name</i> in <i>set or sequence</i><br />
						<i>name</i> in <i>name</i><br />
						<i>name</i> in <i>scalar</i> to <i>scalar</i> by <i>scalar</i><br />
					</code>
					Here, <code><i>scalar</i></code> can be a number, a variable name, a function
					call or an element of a list or sequence.
				</div>
				<div id="func-content">
					<b>Procedure</b><br />

					The basic template of a procedure (function) looks like the following: <br />
					<code>
						procedure <i>name</i> ( <i>params</i> )<br />
							<i>code</i><br />
						endproc<br />
					</code>
					In this, <code><i>params</i></code> look like this: <br />
					<code>
						<i>name</i></code> or: <br /><code>
						<i>name</i>, <i>name</i>, ...
					</code>
					<br /><br />

					In a function, you can use a return statement: <br />
					<code>
						return</code> or: <br /><code>
						return <i>expression</i>
					</code><br />
					with <code><i>expression</i></code> containing only a variable 
					or value or a calculation.
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-9 col-12">
		<div class="algorithm box">
			<b>Algorithm</b>
			<!-- Classification Algo input -->
			<form action="{% url 'ab_ui:submit' %}" method="post">
				{% csrf_token %} <!-- used against Cross Site Request Forgeries -->
	
				<textarea id="build-frame" name="code">{% if input %}{{input}}{% endif %}</textarea>
				
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="submitType" id="parse_only" value="parse_only" checked>
					<label class="form-check-label" for="parse_only">Parse</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="submitType" id="parse_and_class" value="parse_and_class">
					<label class="form-check-label" for="parse_and_class">Parse And Classify</label>
				</div>
				
				<div class="btn-group alg-btns" role="group">
					<button type="button" class="btn" id="resetBtn">Reset</button>
					<button type="submit" class="btn">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6 col-12">
		<div class="algorithm-out box">
			<!-- Output parsed Algorithm -->
			<b>Parsed Algorithm</b>
			<div class="result">
				{% autoescape off %}{{ code }}{% endautoescape %}
			</div>
			<div class="complexity" id="complexity">
				Runtime Complexity: {% if complexity %} {{complexity}} {% else %} <i>Not calculated yet.</i> {% endif %}
			</div>
		</div>
	</div>
	<div class="col-md-6 col-12">
		<div class="classific box">
			<!-- Classification and hints parsed Algorithm -->
			<b>How to optimize your Algorithm</b>
			{% if classification %}
			<div class="result" id="help">
				You can optimize your algorithm using <b id="classify">{{ classification }}</b> (probability: {{ probability }}).<br /><br />

				Hints on how to optimize your algorithm:<br />
				{% autoescape off %}{{ tips }}{% endautoescape %}
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

AlgoBooster/ab_ui/templates/ab_ui/base.html
<!doctype html>
{% load static %} 

<html>
	<head>
        <!-- meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'ab_ui/style.css' %}" />
        
        <title>AlgoBooster</title> 
	</head>
	<body>
        <div class="container-fluid">
            <div class="row">
                <!-- Navigation Bar -->
                <div class="col" id="topmenu">
                    <nav class="navbar navbar-expand-md navbar-dark">
                        <a class="navbar-brand" href="{% url 'ab_ui:index' %}">AlgoBooster</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ab_ui:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ab_ui:about' %}">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ab_ui:algobooster' %}">Use AlgoBooster</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'ab_ui:training' %}">Train AlgoBooster</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- main content -->
            <div class="main-content">
                    
                    {% block body_block %}{% endblock %}
                    
            </div>

            <!-- footer -->
            <div class="row">
                <div class="col" id="footer">
                    <nav class="navbar navbar-expand-md navbar-dark">
                        <div class="link-group ml-auto mr-auto">
                            <a href="{% url 'ab_ui:imprint' %}">Imprint</a> &nbsp; &nbsp;
                            <a href="{% url 'ab_ui:disclaimer' %}">Disclaimer</a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

        <!-- JQuery JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <!-- Custom JS -->
        <script src="{% static 'ab_ui/componentInfo.js' %}" ></script>
        <script src="{% static 'ab_ui/btnFuncs.js' %}" ></script>
	</body>			
</html>

AlgoBooster/ab_ui/templates/ab_ui/disclaimer.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
		<div class="col">
			<br /><br />
			<h3>Disclaimer</h3>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col">
                <b>Here is an example for a disclaimer</b><br /><br />

                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<br /><br />

                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
		</div>
	</div>


{% endblock %}

AlgoBooster/ab_ui/templates/ab_ui/imprint.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
		<div class="col">
			<br /><br />
			<h3>Imprint</h3>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col">
            Daniela Böing<br />
            Westring 50<br />
            44623 Herne<br />
            Germany
		</div>
	</div>


{% endblock %}

AlgoBooster/ab_ui/templates/ab_ui/index.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
		<div class="col">
			<br /><br />
			<h1>AlgoBooster</h1>
			<h2>Optimize Your Algorithms</h2>
			<br /><br />
		</div>
	</div>
	<div class="row">
		<div class="col">
			<figure>
				<center>
					<img src="{% static 'ab_ui/img/placeholder.jpg' %}" id="teaser-img">
				</center>
			</figure>
		</div>
	</div>
	<div class="row">
			<div class="col">
				<br /><br />
				<h5>Get to the Application <a href="{% url 'ab_ui:algobooster' %}">right away</a>
					and test your very own algorithm.</h5>
				<br /><br />
			</div>
		</div>


{% endblock %}

AlgoBooster/ab_ui/templates/ab_ui/training.html
{% extends 'ab_ui/base.html' %}
{% block body_block %}
{% load static %} 

<div class="row">
	<div class="col">
		<br />
		<h3>Train AlgoBooster</h3>
		<br />
	</div>
</div>

<div class="row">
	<div class="col-12">
		<div class="algorithm box">
			<b>Algorithm</b>
			<!-- Train Algo Input -->
			<form action="{% url 'ab_ui:train' %}" method="post">
				{% csrf_token %} <!-- used against Cross Site Request Forgeries -->
	
				<textarea id="train-frame" name="code">{% if input %}{{input}}{% endif %}</textarea>
				                
                <div class="form-check form-check-inline">
                    <label class="form-check-label" id="label-class">Classification: </label>
				</div>

				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="none" value="0" {% if classification == '0' %} checked {% endif %}>
					<label class="form-check-label" for="none">None</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="divAndConq" value="1" {% if classification == '1' %} checked {% endif %}>
					<label class="form-check-label" for="divAndConq">Divide And Conquer</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="dynProg" value="2" {% if classification == '2' %} checked {% endif %}>
					<label class="form-check-label" for="dynProg">Dynamic Programming</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="bnb" value="3" {% if classification == '3' %} checked {% endif %}>
					<label class="form-check-label" for="bnb">Branch and Bound</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="greedy" value="4" {% if classification == '4' %} checked {% endif %}>
					<label class="form-check-label" for="greedy">Greedy Algorithm</label>
				</div>
				<div class="form-check form-check-inline">
					<input class="form-check-input" type="radio" name="classification" id="randalg" value="5" {% if classification == '5' %} checked {% endif %}>
					<label class="form-check-label" for="randalg">Randomized Algorithm</label>
				</div>
				
				<div class="btn-group alg-btns" role="group">
					<button type="button" class="btn" id="resetBtn">Reset</button>
					<button type="submit" class="btn">Submit</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-12">
		<!-- Training output -->
		<div class="algorithm-out box">
			<b>Result</b>
			<div class="result">
				{% if result %}{{ result }}{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}